
Metadata:
  siteID: TMP
  estYear: 2999
  lat: 90       
  long: 0
  TimeZoneHour: 0
  northOffset: 360
Processing:
  ThirdStage:
    Fluxes:
      # Names of flux variables as they come in from second stage
      # For fluxes that do not apply, change the key-value pair to NULL (see FNO2 example)
      # *** DOUBLE CHECK FLUX NAMES ON RHS MATCH SECOND STAGE TRACES ***
      H: H
      LE: LE
      NEE: FC
      FCH4: FCH4
      FNO2: NULL
    Met_Gap_Filling:
      Linear_Interpolation:
        # *** DOUBLE CHECK VARIABLE NAMES ON RHS MATCH SECOND STAGE TRACE NAMES ***
        Fill_Vars: TA_1_1_1,RH_1_1_1,VPD_1_1_1
    Standard_Cleaning:
      # Filter out values  #+/- wakeFilter of northOffset +/- 180 degrees
      wakeFilter: 30
      # If you do not want fluxes filtered during rain events, set to NULL
      precipCutOff: 0
    Storage_Correction:
      # If storage terms are missing, then set Run: FALSE
      Run: TRUE
    JS_Moving_Z: 
      # You can turn off z-score filtering by setting Run: FALSE
      Run: TRUE
    Papale_Spike_Removal:
      # You can turn off MAD filtering by setting Run: FALSE
      Run: TRUE
    REddyProc:
      # You can turn off REddyProc by setting Run: FALSE
      # Setting Run: FALSE would normally only be for diagnostic purposes.
      Run: TRUE
      Ustar_filtering:
        # Keep "run_defaults" as TRUE to run "fast" ustar filtering
        # If run_defaults = FALSE, conduct "full_uncertainty" 
        run_defaults: TRUE
      vars_in:
        # Variables to feed to REddyProc (from second stage)
        # Key is REddyProc name, val is database name (or previous output from up the processing chain)
        # Fluxes will be whatever the most "up to date" filtered variable is
        # e.g., NEE is Storage corrected, spikes removed (Papale 2006), etc.
        #
        # *** Double check that variable names (on the right) match Second Stage naming ***
        # *** If a standard flux is missing set key-val to NULL (e.g. FCH4: NULL) ***
        NEE: NEE
        LE: LE
        H: H
        FCH4: FCH4
        Rg: SW_IN_1_1_1
        Tair: TA_1_1_1
        VPD: VPD_1_1_1
        Ustar: USTAR
        season: season
        # Add additional variables here if needed
        # rH: RH_1_1_1
      # MDS gap filling (will only fill these variables *if* present in "vars_in")
      MDSGapFill:
        # List of Ustar-dependent variables on which to gap-fill using MDS
        UStarScens:
          - NEE
          - LE
          - H
          - FCH4
        # List of variables on which to gap-fill using MDS
        basic: 
          - Rg
          - Tair
          - VPD
          # Add additional variables here if desired
          # - rH
    Flux_Partitioning:
        # You can turn off flux partitioning calculations by setting Run: FALSE
        Run: TRUE
